config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :categories, only: [:create, :index, :show] do
    resources :challenges, only: [:create, :index, :show, :destroy]
  end

  resources :bookings, only: [:new, :create, :show, :destroy]

  get "/play", to: "pages#play"
  get "/gender", to: "pages#gender"
  get "/team", to: "pages#team"
  get "/request_challenge", to: "pages#request_challenge"
  get "/invite", to: "invitations#invite"
  get "/dashboard", to: "bookings#index"
  post "/confirm_challenge", to: "bookings#confirm_challenge"
  get "/validate_challenge", to: "bookings#validate_challenge"
  get "/congrats", to: "congrats#show"

  namespace :spend do
    resources :bookings, only: [:new, :create]
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :partner, class_name: 'User'
  belongs_to :challenge
  has_one :category, through: :challenge

  validates :status, inclusion: { in: %w(created pending completed failed) } # ['created', 'completed', 'failed']

  scope :new_to_old , -> {order(created_at: :desc)}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable,
           :omniauthable, :omniauth_providers => [:facebook]

  has_many :bookings
  has_many :challenges, through: :bookings
  belongs_to :partner, class_name: "User"

  after_create :send_welcome_email, :assign_partner, :assign_partner_via_email

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first || User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
      end
    return user
  end

  def total_kisses
    return 0 unless partner_id
    user_bookings = bookings.where(status: 'completed')
    earn = (user_bookings.any? ? user_bookings.sum(:kisses) : 0)
    user_bookings = Booking.where(partner_id: self.id, spend: true)
    spend = (user_bookings.any? ? user_bookings.sum(:kisses) : 0)
    earn - spend + 500
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

  def assign_partner_via_email
    partner = User.where(partner_email: email).first
    return nil unless partner
    partner.update(partner_id: id)
    update(partner_id: partner.id, partner_email: partner.email)
  end

  def assign_partner
    if partner_id
      partner = User.find(partner_id)
      partner.partner_id = id
      partner.save
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show]
  skip_before_action :authenticate_user!, only: [:validate_challenge]

  def index
    @bookings = current_user.bookings.new_to_old
    @user = current_user
  end

  def show
  end

  def new
    set_challenges
    @booking = Booking.new
  end

  def create
    challenge = Challenge.find(params[:challenge_ids].split(/\s/).sample)
    @booking = current_user.bookings.build(
      challenge_id: challenge.id,
      status: "created", partner_id: current_user.partner_id, spend: false)
    @booking.kisses = challenge.category.kisses

    if @booking.save
      BookingMailer.challenge_notification(@booking.id).deliver_now if current_user.partner
      redirect_to @booking, notice: 'One challenge has been assigned! Go to your dashboard to view it.'
    else
      set_challenges
      render :new
    end
  end

  def confirm_challenge
    @booking = Booking.find(params[:booking_id]) if current_user.partner
    @booking.update(status: 'pending') if current_user.partner
    BookingMailer.challenge_confirmation(@booking.id, current_user.id).deliver_now if current_user.partner

    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.json
    end
  end

  def validate_challenge
    @booking = Booking.find(params[:booking_id])
    @booking.update(status: 'completed')
    redirect_to dashboard_path
  end

  private

  def set_challenges
    @category = Category.find(params[:category_id])
    gender = current_user.gender
    @old_challenges_ids = current_user.bookings.map(&:challenge_id)
    @sorted_challenges = Challenge.where(category_id: @category.id, gender: [gender, "both"]).where.not(id: @old_challenges_ids).random
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    #params.permit(:seats, :country, :category)
    params.require(:sorted_challenges).permit(:name, :picture, :kisses, :gender)
  end

end

app/controllers/spend/bookings_controller.rb
class Spend::BookingsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:new]

  def new
    @categories = Category.all
  end

  def create
    if current_user.partner.nil?
     redirect_to dashboard_path
     flash[:notice] = "To spend kisses add a partner && win 500 Kisses ;) "
    elsif
      current_user.total_kisses < 500
      redirect_to dashboard_path
      flash[:notice] = "you should have a minium of 500 kisses to Spend kisses"
    else
    category = Category.find(params[:category][:id])
    challenge = category.challenges.where(gender: [current_user.partner.gender, "both"]).sample
    partner_booking = current_user.partner.bookings.build(
    challenge_id: challenge.id,
    partner_id: current_user.id,
    kisses: category.kisses,
    spend: true,
    status: "created")
      if partner_booking.save
      CongratsMailer.spend_challenge(partner_booking.id).deliver_now
      redirect_to congrats_path(category: category.id)
      else
      flash[:error] = "Oops, something went wrong"
      redirect_to play_path
      end
    end
    end
  end

app/views/bookings/confirm_challenge.js.erb
$("#confirm-challenge-button-<%= j @booking.id.to_s %>").html('<button type="button", class="btn btn-success"> Waiting for partner </button>')

app/views/bookings/index.html.erb
<div class="text-center">
  <h1 class="title ">Your dashboard</h1>
</div>

<div class="text-center">
  <% if @user.partner.nil? %>
    <%= link_to "New challenge", play_path, class: "button-lovee button-lovee-modal", id: "dash-btns" %>
    <%= link_to t(".top_call_to_action", default: "Add your partner"), "" , class: "button-lovee button-lovee-modal", id: "dash-btns", "data-toggle" => "modal", "data-target" => "#invitation" %>
  <% else %>
    <%= link_to "New challenge", play_path, class: "button-lovee button-lovee-modal", id: "dash-btns" %>
  <% end %>
</div>

<br>
<br>

<div class="container">
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="flip">
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card">
            <div class="face front">
              <div class="dashboard-card text-center">
                <div class="card-left" id="left-title">
                  <h2 class="heading-yellow"><%= booking.challenge.title%></h2>
                </div>
                <!-- <div class="card-left"> -->
                  <div id="kisses">
                    <%= booking.challenge.category.kisses%> <%= image_tag "tiny_kiss.png" %>
                  </div>
                  <div id="booking-status">
                    Status:  <%= booking.status %>
                  </div>
                  <% if booking.status == "created" %>
                    <div class="col-xs-12">
                      <div class="text-center top-margin-for-done" id="confirm-challenge-button-<%= booking.id %>">
                        <%= link_to "I did it!", "#", class:"booking-validation button-lovee-i-did-it inner-padding", id:"done", "data-booking-id": booking.id %>
                      </div>
                    </div>
                  <% elsif booking.status == "pending" %>
                    <div class="col-xs-12">
                      <div class="text-center">
                        <button type="button", class="button-lovee-i-did-it", id="waiting">  Waiting for partner </button>
                      </div>
                    </div>
                  <% else %>
                  <div class="col-xs-12">
                    <div class="text-center">
                      <button type="button", class="button-lovee-i-did-it", id="completed">  Done!</button>
                    </div>
                  </div>
                  <% end %>
                <!-- </div> -->
                <%= image_tag booking.challenge.category.picture, class: "dashboard-category"%>
              </div>
            </div>
            <div class="face back">
              <div class="dashboard-card text-center">
                <div class="card-left" id="left-title">
                  <h2 class="heading-yellow"><%= booking.challenge.title%></h2>
                </div>
                <%= booking.challenge.description %>
                <%= image_tag booking.challenge.category.picture, class: "dashboard-category"%>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>



<!-- modal for request sent -->
<div class="modal fade" id="request-sent" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content lovee-modal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center heading-blue">Confirmation request sent</h3>
      </div>
      <div class="modal-body text-center">
         <p>
          <% if current_user && current_user.partner && current_user.partner.first_name  %>
            A confirmation request has been sent to <span class="name"> <%= current_user.partner.first_name %></span> . You will get your LoVee kisses as soon as <span class="name"> <%= current_user.partner.first_name %></span> confirms you completed this challenge.
          <% elsif current_user && current_user.partner %>
           A confirmation request has been sent to your partner.
           You will get your LoVee kisses as soon as your partner confirms you completed this challenge.
          <% else %>
            You do not have a partner yet, please add one before sending a confirmation !
        <% end %>
        </p>
        <div class="modal-footer">
          <div class="text-center">
            <button type="button" class="btn button-lovee button-rules button-lovee-small" data-dismiss="modal">OK</button>
          </div>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Modal for inviting partner -->
<div class="modal fade" id="invitation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content lovee-modal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center heading-blue" id="myModalLabel">Invite your partner</h4>
      </div>
      <div class="modal-body">
        <%= form_tag invite_path, method: :get do %>
        <br>
          <p class="text-center">Your partner's email</p>
          <%= email_field_tag :email, nil, class: "form-control", placeholder: "partner@lovee.com" %>
          <br>
          <div class="text-center">
            <%= submit_tag "invite", class: "button-lovee button-lovee-modal", id: "invite" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>




<% content_for :after_js do %>
  <%= javascript_tag do %>
  $(document).ready(function(){

    // -------- triggers flip on click
    $('.flip').click(function(){
      $(this).find('.card').toggleClass('flipped');
    });

    // -------- calls the model and triggers
    $(".booking-validation").click(function(e){
      e.stopPropagation();
      $.ajax({
        method: "post",
        url: "<%= confirm_challenge_path %>",
        data: {booking_id: $(e.target).data("booking-id")}
      });
      $("#request-sent").modal("show");
      $("#confirm-challenge-button-" + $(e.target).data("booking-id")).html('<button type="button", class="button-lovee-i-did-it", id="waiting"> Waiting for partner </button>');

    });

  });
  <% end %>
<% end %>

<!-- confirm_challenge_path(booking_id: booking.id), "data-toggle" => "modal", "data-target" => "#request-sent", remote: true, method: :post -->

app/views/bookings/new.html.erb
<br>
<h2 class="heading-blue text-center">Category - <%= @category.name%></h2>
<h3 class="subheading text-center"> <strong><%= @category.kisses %></strong>  <%= image_tag "tiny_kiss.png" %></h3>
<div class="container">
  <div class="row">
    <% @sorted_challenges.each do |challenge| %>

      <div class="col-xs-12 col-md-4">
        <div class= "card" >
          <div class=" text-center text-align lovee-message">
            <div class="top">
              <p class="challenge-heading"><%= challenge.title %></p>
            </div>
            <p class="yellow-text"> <%= challenge.description[0..70] %> ... </p>
            <!-- <h1 class="red-text"><strong>?</strong></h1> -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>




<div class="container text-center padded-bottom">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="aligner right">
        <%= link_to new_booking_path(category_id: @category.id),class: "button-lovee button-lovee-small" do %>
          Shuffle <i class="fa fa-refresh"></i>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="left">
        <%= form_for @booking do |f| %>
          <%= hidden_field_tag "challenge_ids", @sorted_challenges.map(&:id) %>
          <%= f.button :button, class: 'button-lovee button-lovee-small' do %>
            Get one <i class="fa fa-gamepad"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="text-center">
  <%= link_to "Back", categories_path, class: "btn btn-primary"%>
  <a href="#" data-toggle="modal" data-target="#rules" class="btn btn-primary">Help</a>

</div>
<br>
<br>



<!-- modal -->
<div class="modal fade" id="rules" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content lovee-modal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center heading-blue"><i class="fa fa-gamepad"></i> How to play </h3>
      </div>
      <div class="modal-body text-center">
        <i class="fa fa-random fa-3x marginized"></i>
        <p>You are presented with three <strong>random</strong> challenges</p>

        <i class="fa fa-play fa-3x marginized"></i>
        <p>When you click "Get one", you will be assigned <strong>ONE</strong> of these challenges</p>

        <i class="fa fa-refresh fa-3x marginized"></i>
        <p>If you are unhappy with the selection of challenges, click shuffle!</p>


        <div class="modal-footer">
          <div class="text-center">
            <button type="button" class="btn button-lovee button-rules button-lovee-small" data-dismiss="modal">Got it</button>
          </div>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<!-- <div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <div class= "card" >
        <div class=" text-center text-align send-message">


        </div>
      </div>
    </div>
  </div>
</div>
 -->

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
      <div class= "card" >
        <div class=" text-center text-align lovee-message">
          <h2 class="heading-yellow"> Yay!</h2>
          <br>
          <p> <strong> LoVee </strong> selected the following awesome challenge for you:</p>
          <h3 class="red-text"><%= @booking.challenge.title %></h3>
          <p><%= @booking.challenge.description %></p>
          <p><%= @booking.challenge.category.kisses %>  <%= image_tag "tiny_kiss.png" %></p>




          <div class=" text-center text-align send-message">
            <% if current_user.partner_id.nil? %>
              <p class="red-text">You need a partner to play</p>
              <%= link_to t(".top_call_to_action", default: "Add your partner"), "" , class: "button-lovee btn", id: "good-luck", "data-toggle" => "modal", "data-target" => "#invitation" %>
              <br>
              <br>
              <p><%= link_to "Or go to dashboard", dashboard_path%></p>
            <% else %>
              <%= link_to t(".top_call_to_action", default: " Good luck "), dashboard_path , class: "button-lovee btn", id: "good-luck" %>
            <% end %>
          </div>



        </div>
        </div>
      </div>
    </div>
  </div>

  <br>
  <br>






<!-- Modal -->
<div class="modal fade" id="invitation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content lovee-modal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center heading-blue" id="myModalLabel">Invite your partner</h4>
      </div>
      <div class="modal-body">
        <%= form_tag invite_path, method: :get do %>
        <br>
          <p class="text-center">Your partner's email</p>
          <%= email_field_tag :email, nil, class: "form-control", placeholder: "partner@lovee.com" %>
          <br>
          <div class="text-center">
            <%= submit_tag "invite", class: "button-lovee button-lovee-modal", id: "invite" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>