config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :categories, only: [:create, :index, :show] do
    resources :challenges, only: [:create, :index, :show, :destroy]
  end

  resources :bookings, only: [:new, :create, :show, :destroy]

  get "/play", to: "pages#play"
  get "/gender", to: "pages#gender"
  get "/team", to: "pages#team"
  get "/request_challenge", to: "pages#request_challenge"
  get "/invite", to: "invitations#invite"
  get "/dashboard", to: "bookings#index"
  post "/confirm_challenge", to: "bookings#confirm_challenge"
  get "/validate_challenge", to: "bookings#validate_challenge"
  get "/congrats", to: "congrats#show"

  namespace :spend do
    resources :bookings, only: [:new, :create]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <ul class="list-inline" id="icons-list">
        <li><a href=""><i class="fa fa-instagram"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>

      <div class="col-xs-12 col-sm-4 text-center">
        <ul class="list-unstyled" id="links-list">
          <li><%= link_to "Team", team_path %></li>
          <li><%= link_to "About", "#" %></li>
          <li><%= link_to "Buy kisses", "#" %></li>
        </ul>
      </div>

      <div class="col-xs-12 col-sm-4 text-right">
        <p class="footer-copyright">Made with <i class="fa fa-heart-o" aria-hidden="true"></i> for the love</p>
      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-lovee">
  <!-- Logo -->
  <!-- <div classe="menu">
<p> Lo <i class="fa fa-heart-o" aria-hidden="true"></i> ee</p>
</div> -->
<div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle menu-icon" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-pencil-square-o"></i>  Edit Profile
          <% end %>
        </li>
        <li>
          <%= link_to dashboard_path do %>
            <i class="fa fa-bar-chart"></i>  Dashboard
          <% end %>
        </li>
        <li>
          <%= link_to '#' do %>
            <i class="fa fa-calendar"></i>  Anniversaries
          <% end %>
        </li>
        <li>
          <%= link_to '#' do %>
            <i class="fa fa-heart"></i>  Buy kisses
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: " Log out") %>
          <% end %>
        </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-sign-in"></i> <%= t(".sign_in", default: "Login") %>
            <% end%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>


  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation --><!--
  <div class="navbar-wagon-right hidden-xs hidden-sm"> -->

    <!-- Search form -->
    <!--  <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

     <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%#= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <!-- <div class="badge-container">
          <i class="fa fa-comment-o"></i>
          <div class="badge badge-o">2x</div>
        </div> -->
      <%# end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
          <%= link_to dashboard_path do %>

        <div class="dropdown">
          <% options = {class: "avatar dropdown-toggle", id: "navbar-wagon-menu"} %>
            <% if current_user.facebook_picture_url %>
              <%= image_tag current_user.facebook_picture_url, options %>
              <span class="badge badge-coins"><%= current_user.total_kisses %> ❤</span>
            <% else %>
              <%= image_tag "avatar_default.png", options %>
              <span class="badge badge-coins"><%= current_user.total_kisses %> ❤</span>
            <% end %>

        </div>
        <% end %>
      </div>

      <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
   <!--  <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->

</div>