config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :categories, only: [:create, :index, :show] do
    resources :challenges, only: [:create, :index, :show, :destroy]
  end

  resources :bookings, only: [:new, :create, :show, :destroy]

  get "/play", to: "pages#play"
  get "/gender", to: "pages#gender"
  get "/team", to: "pages#team"
  get "/request_challenge", to: "pages#request_challenge"
  get "/invite", to: "invitations#invite"
  get "/dashboard", to: "bookings#index"
  post "/confirm_challenge", to: "bookings#confirm_challenge"
  get "/validate_challenge", to: "bookings#validate_challenge"
  get "/congrats", to: "congrats#show"

  namespace :spend do
    resources :bookings, only: [:new, :create]
  end

end

app/views/pages/dashboard.html.erb
<div class="text-center">
  <h1 class="title ">Your dashboard</h1>
</div>

<div class="container">
  <div class="row">
    <% @bookings.each do |booking| %>

      <div class="flip">
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card">
            <div class="face front">
              <div class="dashboard-card text-center">
                <div class="card-left" id="left-title">
                  <h2 class="heading-yellow"><%= booking.challenge.title%></h2>
                </div>
                <div class="card-left">
                  <div id="kisses">
                    <%= booking.challenge.category.kisses%> <%= image_tag "tiny_kiss.png" %>
                  </div>
                  <div id="booking-status">
                    <%= booking.status %>
                  </div>
                </div>
                <%= image_tag booking.challenge.category.picture, class: "dashboard-category"%>
              </div>
            </div>
            <div class="face back">
              <div class="dashboard-card text-center">
                <div class="card-left" id="left-title">
                  <h2 class="heading-yellow"><%= booking.challenge.title%></h2>
                </div>
                <%= booking.challenge.description %>
                <%= image_tag booking.challenge.category.picture, class: "dashboard-category"%>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<% content_for :after_js do %>
  <%= javascript_tag do %>
  $(document).ready(function(){
    $('.flip').click(function(){
      $(this).find('.card').toggleClass('flipped');
    });
  });

<% end %>
<% end %>

app/views/pages/dashboard_old.html.erb
<div class="text-center">
  <h1 class="title ">Your dashboard</h1>

</div>

<div class="container">
<div class="text-center">
  <%= image_tag current_user.facebook_picture_url, class: "avatar-large" %>
</div>

  <div class="dashboard-frame">
    <div class="row">
      <div class="col-xs-5">
        <h2 class="yellow-text">Title</h2>
      </div>
      <div class="col-xs-3">
        <h2 class="yellow-text">
          Kisses
        </h2>
      </div>
      <div class="col-xs-2">
        <h2 class="yellow-text">
          Status
        </h2>
      </div>
      <div class="col-xs-2">
        <h2 class="yellow-text">
          Confirm
        </h2>
      </div>
    </div>
    <% @bookings.each do |booking| %>
      <div class="row">
        <div class="col-xs-5 ">
          <p><%= booking.challenge.title %></p>
        </div>
        <div class="col-xs-3">
          <p><%= booking.challenge.category.kisses %></p>
        </div>
        <div class="col-xs-2">
          <p><%= booking.status %></p>
        </div>
        <% if booking.status == "created" %>
          <div class="col-xs-2">
            <a href="#" data-toggle="modal" data-target="#request-sent" class="btn btn-success">Done?</a>
            <!-- <button type="button", class="btn btn-success"> Done? </button> -->
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>


<!-- modal -->
<div class="modal fade" id="request-sent" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content lovee-modal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center heading-blue">Confirmation request sent</h3>
      </div>
      <div class="modal-body text-center">
        <p> A confirmation request has been sent to
        <% if current_user && current_user.partner && current_user.partner. first_name %>
           with <span id="play-name"> <%= current_user.partner.first_name %></span>
          You will get your LoVee kisses as soon as they confirm you completed this challenge.
           <% else %>
            You do not have a partner yet, please add one before sending a confirmation !
        <% end %>
        </p>
        <div class="modal-footer">
          <div class="text-center">
            <button type="button" class="btn button-lovee button-rules button-lovee-small" data-dismiss="modal">OK</button>
          </div>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pages/gender.html.erb
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="gender" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content lovee-modal">
      <div class="modal-header">
        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
        <h3 class="modal-title text-center">Make LoVee yours</h3>
      </div>
      <div class="modal-body text-center">
      <p>Please select your gender </p>
        <%= simple_form_for(current_user, url: user_registration_path, html: { method: :patch }) do |f| %>
          <%= f.error_notification %>
          <div class="gender-list">
          <div class="form-actions text-center">
            <%= f.button :button, class:"btn button-lovee gender-btn marginized", value: 'male', name: 'user[gender]' do %>

                 <i class="fa fa-male"></i>
            <% end %>
          </div>
          <div class="form-actions text-center">
            <%= f.button :button, class:"btn button-lovee gender-btn marginized", value: 'female', name: 'user[gender]' do %>
              <i class="fa fa-female"></i>
            <% end %>
          </div>
        <% end %>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<% content_for :after_js do %>
  <%= javascript_tag do %>
    $( document ).ready(function() {
      $("#gender").modal('show') ;
    });
  <% end %>
<% end %>

app/views/pages/home.html.erb
<div class="nav-and-banner-container">


<div class="navbar-lovee">
<div class="navbar-wagon-item">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle menu-icon" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu navbar-wagon-dropdown-menu">
      <% if user_signed_in? %>
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-pencil-square-o"></i>  Edit Profile
          <% end %>
        </li>
        <li>
          <%= link_to dashboard_path do %>
            <i class="fa fa-bar-chart"></i>  Dashboard
          <% end %>
        </li>
        <li>
          <%= link_to '#' do %>
            <i class="fa fa-calendar"></i>  Anniversaries
          <% end %>
        </li>
        <li>
          <%= link_to '#' do %>
            <i class="fa fa-heart"></i>  Buy kisses
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: " Log out") %>
          <% end %>
        </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-sign-in"></i> <%= t(".sign_in", default: "Login") %>
            <% end%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>


  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

     <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
          <%= link_to dashboard_path do %>

        <div class="dropdown">
          <% options = {class: "avatar dropdown-toggle", id: "navbar-wagon-menu"} %>
            <% if current_user.facebook_picture_url %>
              <%= image_tag current_user.facebook_picture_url, options %>
              <span class="badge badge-coins"> <%=current_user.total_kisses %> ❤</span>
            <% else %>
              <%= image_tag "avatar_default.png", options %>
              <span class="badge badge-coins"> <%=current_user.total_kisses %> ❤</span>
            <% end %>

        </div>
        <% end %>
      </div>

      <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>


<%= render 'shared/flashes' %>

<!-- <div class="banner"> -->
<div class="banner">
  <div class="banner-content">
    <h2><span style="color:#E76E56">LoVee</span>'s in the air</h2>
    <br>
    <% if user_signed_in? %>
      <%= link_to t(".top_call_to_action", default: " Play Now "), play_path , class: "button-lovee btn" %>
    <% else %>
      <%= link_to t(".top_call_to_action", default: " Play Now "), play_path , class: "button-lovee btn" %>
    <% end %>
  </div>
</div>
</div>

<!-- Motto -->
<!-- <div class="motto">
  <div class="container text-align text-center">
  <h2> LoVe.each do | other | </h2>
  </div>
</div> -->

<!-- About the game  -->
<div class="wrapper-lovee padded">
  <div class="container text-align text-center">
    <div class="row">
      <div class="col-xs-12 col-md-4">
        <div >
          <h2><span>Play</span></h2>
          <div class="icons-size">
            <i class="fa fa-gamepad lovee-icon" aria-hidden="true"></i>
          </div>
          <div class="justify">
            <p> A New gaming <strong>Experience</strong> for your <strong> Relationship </strong> Momentum ! </p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
        <div >
          <h2><span>Earn</span></h2>
          <div class="icons-size">
            <i class="fa fa-money lovee-icon" aria-hidden="true"></i>
          </div>
          <div class="justify">
            <p> Receive LoVee <strong>kisses</strong> when you complete a <strong>challenge!</strong> </p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
        <div >
          <h2><span>Love</span></h2>
          <div class="icons-size">
            <i class="fa fa-gratipay lovee-icon" aria-hidden="true"></i>
          </div>
          <div class="justify">
            <p> Spend your <strong>LoVee</strong> kisses and <strong> love </strong> each other ! </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- About the game  -->
<div class="padded about">
  <div class="container text-align text-center">
    <h2> Why ?</h2>
    <p> LoVee is a digital experience which helps couples to re-invent their love every single day.</p>
    <p> With LoVee you will challenge each other for a maximum of fun in your daily life</p>
  </div>
</div>

app/views/pages/not_available.html.erb
<div class="text-center lovee-message">
  <h1>Sorry, this feature is not available yet :/ </h1>
  <p>Please check back soon!</p>
  <%= link_to "Back to main", root_path %>
</div>

app/views/pages/play.html.erb
<div class="text-center">
  <h1 class="title">Let's play
    <% if current_user && current_user.partner && current_user.partner. first_name %>
      with <span id="play-name"> <%= current_user.partner.first_name %></span>
    <% end %>
  </h1>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="play-card">
          <%= link_to "Win kisses", categories_path, class: "button-lovee btn" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="play-card">
          <%= link_to "Spend your kisses", new_spend_booking_path, class: "button-lovee btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/request_challenge.html.erb
<div class="text-center lovee-message">
  <h1>Sorry, this feature is not available yet :/ </h1>
  <p>Please check back soon!</p>
  <%= link_to "Back to main", root_path %>
</div>

app/views/pages/team.html.erb
<div class="text-center">
  <h1 class="title">Here is the Gurus of LoVee world</h1>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
      <div class="play-card ">
          <h3 class="yellow-text"> Stan "the Man "</h3>
          <p class="red-text"> Favorite LoVee quote : "All, everything that I understand, I only understand because I love." </p>
      </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="play-card">
          <h3 class="yellow-text"> Debster "the Webster "</h3>
          <p class="red-text"> Favorite LoVee quote : "In order to be happy oneself it is necessary to make at least one other person happy." </p>
        </div>
      </div>
     </div>
   </div>
 </div>
 </div>