config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :categories, only: [:create, :index, :show] do
    resources :challenges, only: [:create, :index, :show, :destroy]
  end

  resources :bookings, only: [:new, :create, :show, :destroy]

  get "/play", to: "pages#play"
  get "/gender", to: "pages#gender"
  get "/team", to: "pages#team"
  get "/request_challenge", to: "pages#request_challenge"
  get "/invite", to: "invitations#invite"
  get "/dashboard", to: "bookings#index"
  post "/confirm_challenge", to: "bookings#confirm_challenge"
  get "/validate_challenge", to: "bookings#validate_challenge"
  get "/congrats", to: "congrats#show"

  namespace :spend do
    resources :bookings, only: [:new, :create]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :challenges

  after_create do |category|
    category.picture = "category_#{category.name.downcase}.png"
    category.save
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  skip_before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
    session[:show_category_counter] = session[:show_category_counter].nil? ? 1 : session[:show_category_counter] + 1
    @challenges = Challenge.where(category_id: @category.id)
    if user_signed_in?
      gender = user.gender
      @gender_challenges = Challenge.where(gender: gender)
      @sorted_challenges = @gender_challenges.random
    else
      @sorted_challenges = @challenges.random
    end
  end
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    #params.permit(:seats, :country, :category)
    params.require(:category).permit(:name, :picture, :kisses)
    @gender = challenge.gender
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1 class = "text-center title">Choose a category</h1>

<div class="container">
  <div class="row">

    <% @categories.each do |category| %>
      <div class="col-xs-12 col-md-4">
        <div class="category-card text-center">
          <% if user_signed_in? %>
            <%= link_to new_booking_path(category_id: category.id), class: "category-card-link" do %>
              <h1 class="call-to-action-font"><%= category.name %></h1>
              <%= image_tag category.picture, class: "category-card-image "%>
              <h3>You can earn: <%= category.kisses %>  <%= image_tag "tiny_kiss.png" %></h3>
            <% end %>
          <% else %>
            <%= link_to category_path(category), class: "category-card-link" do %>
              <h1 class="call-to-action-font"><%= category.name %></h1>
              <%= image_tag category.picture, class: "category-card-image"%>
              <h3> <%= category.kisses %>  <%= image_tag "tiny_kiss.png" %> </h3>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<div class="text-center">
  <%= link_to "Back", play_path, class: "button-lovee button-lovee-small", id: "back"%>
</div>

app/views/categories/show.html.erb
<br>
<h2 class="heading-blue text-center">Category - <%= @category.name%></h2>
<h3 class="subheading text-center"><strong><%= @category.kisses %></strong>  <%= image_tag "tiny_kiss.png" %></h3>

<div class="container">
  <div class="row">
    <% @sorted_challenges.each do |challenge| %>

      <div class="col-xs-12 col-md-4">
        <div class= "card" >
          <div class=" text-center text-align lovee-message">
            <div class="top">
              <p class="challenge-heading"><%= challenge.title %></p>
            </div>
            <p class="yellow-text"> <%= challenge.description[0..70] %> ... </p>
            <!-- <h1 class="red-text"><strong>?</strong></h1> -->
            <!-- <p class="yellow-text">for <%=challenge.gender%></p> -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>
<div class="container text-center padded-bottom">
  <%= link_to category_path(@category), class: "button-lovee button-lovee-small" do %>
    Shuffle <i class="fa fa-refresh"></i>
  <% end %>
  <%= link_to new_user_session_path, class: "button-lovee button-lovee-small" do%>
     Get one <i class="fa fa-gamepad"></i>
  <% end %>
</div>
<div class="text-center">
  <%= link_to "Back", categories_path, class: "btn btn-primary"%>
  <a href="#" data-toggle="modal" data-target="#rules" class="btn btn-primary">Help</a>
</div>
<br>
<br>

<div class="modal fade" id="rules" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content lovee-modal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center heading-blue"><i class="fa fa-gamepad"></i> How to play </h3>
      </div>
      <div class="modal-body text-center">
        <i class="fa fa-random fa-3x marginized"></i>
        <p>You are presented with three <strong>random</strong> challenges</p>

        <i class="fa fa-play fa-3x marginized"></i>
        <p>When you click "Get one", you will be assigned <strong>ONE</strong> of these challenges</p>

        <i class="fa fa-refresh fa-3x marginized"></i>
        <p>If you are unhappy with the selection of challenges, click shuffle!</p>


        <div class="modal-footer">
          <div class="text-center">
            <button type="button" class="btn button-lovee button-rules button-lovee-small" data-dismiss="modal">Got it</button>
          </div>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<% content_for :after_js do %>
  <%= javascript_tag do %>
    $( document ).ready(function() {
      if (<%= session[:show_category_counter] %> === 1) {
        setTimeout(function() {
          $('#rules').modal('show');
        }, 1000);
      }
    });

  <% end %>
<% end %>